FRONTENDBOOTCAMP-13th/Final-07-Chillin-Code

.gitmessage.txt
=> 📝 Docs: 탬플릿 파일 내용 수정

src/styles/reset/modern-reset.css
- docs/modern-reset/jinseob
- **변경 내용**:  modern reset 파일 추가
- **관련 이슈**:  #13 
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> 🐳 chore: modern reset 파일 추가

src/app/layout.tsx, src/components/layout/header.tsx, src/styles/components/header.module.css, src/styles/globals.css
- Feature/header/jinseob
- **변경 내용**:  모바일 header UI 구현 및 global.css 배경색 수정
- **관련 이슈**: #9 
- [X ] 기능 추가
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- [X ] 코딩 컨벤션 준수
- [ X] 자체 코드 리뷰 완료
- [ X] 필요한 주석 추가
- 
-
=> ✨ Feat: 모바일 header UI 구현

src/app/layout.tsx, src/components/layout/header.tsx, src/styles/components/header.module.css
- 
- **변경 내용**: Web Header UI 구현
- **관련 이슈**:  #9 
- [ x] 기능 추가
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- [ x] 코딩 컨벤션 준수
- [ x] 테스트 케이스 추가/수정
- 
-
=> ✨ feat: Web Header UI 구현

src/app/layout.tsx, src/app/login/page.tsx, src/app/login/signUp/page.tsx, src/styles/login/login.module.css, src/styles/login/signUp.module.css
- Feature/user auth/yuha
- **변경 내용**: login 페이지 UI 구현
- **관련 이슈**: `#17`
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ✨ Feat: 로그인, 회원가입 페이지 구현

public/icons/white-menu-icon.svg, src/components/layout/header.tsx, src/styles/components/header.module.css
- 
- **변경 내용**:  Header 반응형 UI 구현
- **관련 이슈**:  #9 
- [x ] 버그 수정
- [ x] 기능 추가
- [ x] 주요 변경 (Breaking Change)
- [ x] 리팩토링
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- [x ] 테스트 케이스 추가/수정
- 
- Header UI의 반응형 break point은 480px(모바일 뷰) 481px~ 650px ~ 768px~ (웹뷰) 로 구분지었습니다.
=> ✨ feat: Header 반응형 UI 구현

src/app/myPage/page.tsx, src/styles/myPage/myPage.module.css
- feature/my-page/yuha
- **변경 내용**: mypage UI 구현
- **관련 이슈**: `#24`
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ✨ feat: mypage UI 구현

src/app/layout.tsx, src/app/zip-code/page.tsx, src/styles/zip-code/zip-code.module.css
- 
- **변경 내용**: 우편번호찾기 페이지 UI 구현
- **관련 이슈**:  #39 
- [ X] 기능 추가
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- [X ] 코딩 컨벤션 준수
- [X ] 자체 코드 리뷰 완료
- [X ] 필요한 주석 추가
- 
-
=> ✨ feat : 우편번호찾기 페이지 UI 구현

src/components/layout/myPageMobileHeader.tsx
- 
- **변경 내용**:  my-page Header 아이콘 경로 수정
- **관련 이슈**: #31 
- [ x] 버그 수정
- [ x] 리팩토링
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- [ x] 코딩 컨벤션 준수
- 
- 아이콘을 상대경로로 잘못 작성하여 하위 페이지에서는 아이콘을 찾지 못하는 버그를 발견하여 경로를 수정하였습니다.
=> ♻️ refactor : my-page Header 아이콘 경로 수정

src/components/layout/myPageHeader.tsx
- 
- **변경 내용**: 
- **관련 이슈**: #9 
- [ x] 버그 수정
- [x ] 리팩토링
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-  검색 아이콘 경로 수정했습니다.
=> ♻️ refactor : my page Header Icon 경로 수정

src/app/zip-code/page.tsx, src/components/layout/header.tsx
- 
- **변경 내용**:  mobile zip-code page 아이콘 경로 수정
- **관련 이슈**: #39 
- [x ] 리팩토링
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
- 아이콘과 로고 경로 수정했습니다.
=> ♻️  refactor : mobile zip-code page 아이콘 경로 수정

src/components/common/check-box.tsx, src/styles/components/check-box.module.css
- feature/checkBox/jinseob
- **변경 내용**: checkBox 컴포넌트 제작
- **관련 이슈**: 
- [x ] 기능 추가
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
- 라디오 체크박스와 체크박스 컴포넌트입니다.
=> ✨ feat : checkBox 컴포넌트 제작

src/app/myPage/orderDelivery/page.tsx, src/styles/myPage/orderDelivery.module.css
- feature/order-delivery/yuha
- **변경 내용**: order delivery 웹, 모바일 뷰 반응형 UI 구현
- **관련 이슈**: `#25`
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ✨ feat : order delivery 웹, 모바일 뷰 반응형 UI 구현

src/app/myPage/orderDelivery/page.tsx, src/styles/myPage/orderDelivery.module.css
- refactor/order-delivery-text/yuha
- **변경 내용**: 모바일 '조회내역이 없습니다.' text 추가
- **관련 이슈**: `#56`
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ♻️ refactor: order delivery text 추가

src/styles/components/header.module.css
- refactor/mobileheaderUI/jinseob
- **변경 내용**: :mobile header UI gap 수정
- [x ] 버그 수정
- [ x] 리팩토링
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- [ x] 필요한 주석 추가
- 
- 320px일때 간격이 넘쳐나는 현상을 수정하였습니다.
=> ♻️ refactor :mobile header UI gap 수정

src/app/detailPage/shippingPolicy/page.tsx, src/styles/detailPage/shippingPolicy/shippingPolicy.module.css
- feature/shipping-policy/yuha
- **변경 내용**: 배송정책 안내 페이지 UI 구현
- **관련 이슈**: `#63`
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ✨ Feat: 배송정책 안내 페이지 UI 구현

src/app/layout.tsx, src/app/myPage/accountDelete/page.tsx, src/styles/myPage/accountDelete/accountDelete.module.css
- feature/accountDelete/jinseob
- **변경 내용**:  모바일 뷰 회원탈퇴 UI 구현
- **관련 이슈**:  #73 
- [ X] 기능 추가
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- [X ] 코딩 컨벤션 준수
- [X ] 자체 코드 리뷰 완료
- [ X] 필요한 주석 추가
- [ X] 영향도 분석 완료
- 
-
=> ✨ feat : 모바일 뷰 회원탈퇴 UI 구현

src/components/common/button.tsx, src/styles/components/button.module.css
- feature/button-components/juno
- **변경 내용**: 
- **관련 이슈**: #83 
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ✨ Feat: 버튼 컴포넌트 추가

src/components/layout/header.tsx, src/pages/category.module.css, src/pages/category.tsx
- feature/mobile-category/juno
- **변경 내용**: 
- **관련 이슈**: #61
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ✨ Feat: 모바일 카테고리 페이지 구현

src/app/layout.tsx, src/app/myPage/marketingAgreement/page.tsx, src/styles/myPage/marketingAgreement/marketingAgreement.module.css
- feature/marketingAgreement/jinseob
- **변경 내용**: web 마케팅 수신동의 UI 구현
- **관련 이슈**:  #72 
- [ x] 기능 추가
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ✨  feat : web 마케팅 수신동의 UI 구현

src/styles/myPage/marketingAgreement/marketingAgreement.module.css
- refactor/marketingAgreement/jinseob
- **변경 내용**: 마케팅 수신동의 UI 간격 수정
- **관련 이슈**: 
- [ x] 기능 추가
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- x ] 코딩 컨벤션 준수
- 
-
=> ♻️ refactor : 마케팅 수신동의 UI 간격 수정

src/app/zipCode/page.tsx, src/styles/zipCode/zip-code.module.css
- feature/zipCodeUI/jinseob
- **변경 내용**: web zipCode 페이지 UI 구현
- **관련 이슈**:  #80 
- [ x] 기능 추가
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ✨ feat : web zipCode 페이지 UI 구현

src/app/detailPage/page.tsx, src/styles/detailPage/detailPage.module.css
- feature/detail-page/yuha
- **변경 내용**: feat : detail page 반응형 UI 구현
- **관련 이슈**: `#87`
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ✨ feat : detail page 반응형 UI 구현

src/app/layout.tsx
- refactor/layout/jinseob
- **변경 내용**: : layout 파일 console.log 삭제
- [x ] 버그 수정
- [x ] 리팩토링
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- [x ] 영향도 분석 완료
- 
-
=> ♻️  refactor : layout 파일 console.log 삭제

src/app/myPage/rewards/page.tsx
- refactor/rewards/jinseob
- **변경 내용**:  rewards 페이지 UI 간격 수정
- [x ] 리팩토링
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ♻️ refactor : rewards 페이지 UI 간격 수정

src/app/myPage/rewards/page.tsx, src/styles/myPage/rewards/rewards.module.css
- refactor/rewards/jinseob
- **변경 내용**: rewards 페이지 UI 수정
- [x ] 리팩토링
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ♻️ refactor : rewards 페이지 UI 수정

src/components/layout/header.tsx, src/components/layout/headerHamburgerMenu.tsx, src/styles/components/header.module.css, src/styles/components/headerHamburgurMenu.module.css
- feature/headerHamburgurUI/jinseob
- **변경 내용**: header UI Link 연결
- [ x] 기능 추가
- [x ] 리팩토링
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- [ x] 코딩 컨벤션 준수
- 
- 햄버거 버튼 구현 및 링크들을 연결하였습니다.
=> ♻️ refactor : header UI Link 연결

src/styles/globals.css
- refactor/global/jinseob
- **변경 내용**: global.css 코드 수정
- **관련 이슈**:  #131 
- [ x] 리팩토링
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ♻️ refactor : global.css 코드 수정

src/styles/detailPage/detailPage.module.css, src/styles/detailPage/shippingPolicy/shippingPolicy.module.css, src/styles/login/login.module.css, src/styles/login/signUp.module.css, src/styles/myPage/addShippingAddress/addShippingAddress.module.css, src/styles/myPage/addressManagement/addressManagement.module.css, src/styles/myPage/cancelReturnExchange.module.css, src/styles/myPage/myPage.module.css, src/styles/myPage/orderDelivery.module.css, src/styles/myPage/wishlist.module.css
- refactor/css/yuha
- **변경 내용**: module.css 관련 수정
- **관련 이슈**: `#133`
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ♻️ refactor : module.css 관련 수정

api/dbinit/team/data.js, src/app/categoryPage/mobile/page.tsx, src/app/categoryPage/mobile/productCard.tsx, src/app/categoryPage/mobile/productGrid.tsx, src/app/categoryPage/web/categoryPage.tsx, src/app/recentPage/mobile/product.tsx, src/app/types/productType.ts, src/styles/categoryPage/mobile/categoryHeader.module.css, src/styles/categoryPage/mobile/categoryPage.module.css, src/styles/categoryPage/mobile/categoryProductCard.module.css, src/styles/categoryPage/mobile/categoryProductGrid.module.css, src/styles/categoryPage/web/categoryPage.module.css, src/styles/mainPage/mainPage.module.css, src/styles/mainPage/sections/productSection.module.css, src/styles/mainPage/sections/reviewSection.module.css, src/styles/recentPage/mobile/recentProduct.module.css, src/styles/recentPage/web/recentProduct.module.css
- 
- **변경 내용**: 
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ♻️ Refactor: css.module 관련 오류 리펙토링

src/app/categoryPage/mobile/page.tsx, src/app/categoryPage/mobile/productGrid.tsx, src/app/recentPage/web/page.tsx, src/app/recentPage/web/product.tsx
- 
- **변경 내용**: 
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> 빌드 과정에서 대소문자 구별 못하는 오류 수정

src/zustand/userStore.ts
- 
- **변경 내용**: 
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> 🔧 Fix: type 경로 수정

api/dbinit/team/data.js
- feature/data/yuha
- **변경 내용**: order 추가
- **관련 이슈**: `#149`
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ✨ feat : order 추가

src/app/categoryPage/mobile/filterModal.tsx, src/app/categoryPage/mobile/productCard.tsx, src/app/categoryPage/web/categoryPage.tsx, src/app/recentPage/mobile/product.tsx, src/app/recentPage/web/product.tsx, src/styles/globals.css, src/styles/mainPage/sections/eventSection.module.css
- refactor/fix-build/juno
-
- **변경 내용**:  2차 배포를 위한 build 오류 수정
- **관련 이슈**: #156 
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ♻️ Refactor: 2차 배포를 위한 build 오류 수정

src/components/layout/myPageHeader.tsx
- refactor/myPageHeaderUI/jinseob
- **변경 내용**: myPageHeader 경로수정
- [ x] 버그 수정
- [x ] 리팩토링
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- [ x] 필요한 주석 추가
- 
-
=> ♻️ refactor : myPageHeader 경로수정

src/app/myPage/rewards/page.tsx
- refactor/rewards/jinseob
- **변경 내용**:  rewards 페이지 사이드바 수정
- **관련 이슈**: 
- [x ] 기능 추가
- [ x] 리팩토링
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- [ x] 필요한 주석 추가
- [x ] 영향도 분석 완료
- 
-
=> ♻️ refactor : rewards 페이지 사이드바 수정

src/app/products/[id]/mobileDetailContent.tsx, src/app/products/[id]/prouctDetailCalc.tsx
- refactor/shoppingCart/jinseob
- **변경 내용**: refactor : 모바일 장바구니 기능 추가 구현
- [x ] 기능 추가
- [x ] 리팩토링
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- [ x] 코딩 컨벤션 준수
- [ x] 필요한 주석 추가
- [x ] 영향도 분석 완료
- 
-
=> ♻️ refactor : 모바일 장바구니 기능 추가 구현

src/app/categoryPage/web/categoryPage.tsx, src/app/mainPage/sections/productSection.tsx
- 
- **변경 내용**: 
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> 🔧 Fix: 3차 배포를 위한 오류 수정

api/dbinit/team/data.js, src/app/myPage/stamp/StampWebMainContent.tsx, src/app/myPage/stamp/StampWebSideContent.tsx, src/app/myPage/stamp/StampWebSideToast.tsx, src/app/myPage/stamp/StampWebToast.tsx, src/app/myPage/stamp/stampMobileBoard.tsx, src/app/myPage/stamp/stampMobileToast.tsx, src/app/shoppingcart/mobileCartView.tsx, src/app/shoppingcart/webCartView.tsx, src/styles/shoppingCart/shoppingCart.module.css, src/styles/stamp/stamp.module.css
- refactor/stamp/jinseob
- **변경 내용**: stamp 오류 수정
- [x ] 버그 수정
- [ x] 리팩토링
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- [x ] 영향도 분석 완료
- 
-
=> ♻️ refactor : stamp 오류 수정

src/app/categoryPage/mobile/categoryClient.tsx, src/app/categoryPage/mobile/page.tsx, src/app/categoryPage/web/categoryPage.tsx, src/app/categoryPage/web/page.tsx, src/components/layout/header.tsx, src/styles/components/header.module.css, src/styles/mainPage/sections/productSection.module.css, src/styles/mainPage/sections/reviewSection.module.css
- 
- **변경 내용**: 
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ♻️ Refactor: 카테고리 탭 필터 초기화 기능 추가

src/app/myPage/orderDelivery/mobilePeriodSearch.tsx, src/app/myPage/orderDelivery/webOrderDeliveryView.tsx
- refactor/today-list/yuha
- **변경 내용**: Refactor: 오늘 주문한 내역 바로 조회
- **관련 이슈**: `#198`
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ♻️ Refactor: 오늘 주문한 내역 바로 조회

src/styles/stamp/stamp.module.css
- refactor/stampToast/jinseob
- **변경 내용**:  stamp coffeti 크기 수정
- [x ] 리팩토링
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ♻️ refactor : stamp coffeti 크기 수정

src/app/myPage/stamp/StampWebSideToast.tsx, src/app/myPage/stamp/StampWebToast.tsx, src/app/myPage/stamp/stampMobileToast.tsx
- refactor/stampToast/jinseob
- **변경 내용**:  stampToast 이미지 경로 수정
- [ x] 리팩토링
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ♻️ refactor : stampToast 이미지 경로 수정

src/app/products/[id]/webDetailContent.tsx
- 
- **변경 내용**: 
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ♻️ Refactor: 인기상품 영역 수정

api/dbinit/team/data.json
- 
- **변경 내용**: 
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> 🔧 Fix: data.json 수정

src/app/mainPage/page.tsx, src/app/mainPage/sections/productSection.tsx, src/app/mainPage/sections/reviewSection.tsx, src/app/products/[id]/mobileDetailContent.tsx, src/app/products/[id]/webDetailContent.tsx, src/app/recentPage/mobile/product.tsx, src/app/recentPage/web/product.tsx, src/styles/detailPage/detailPage.module.css
- 
- **변경 내용**: 
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> ♻️ Refactor: 오류 수정

src/app/products/[id]/webDetailContent.tsx, src/styles/detailPage/detailPage.module.css
- 
- **변경 내용**: 
**테스트 케이스**:
1. 
2. 
**테스트 환경**:
- OS: 
- 브라우저/디바이스: 
- 버전: 
- 
-
=> 🔧 Fix: 이미지 경로 수정
